replicaCount: 2
image: angryjavadeveloper/e-shop:latest

service:
  type: LoadBalancer
  port: 8000
  targetPort: 8000

deployment:
  serverPort: 8000

ingress:
  hosts:
    host: arch.homework
    paths:
      path: /
      pathType: Prefix

externalPostgresql:
  postgresqlUsername: YWRtaW4=
  postgresqlPassword: cGFzc3dvcmQ=
  postgresqlDatabase: eshopdb
  postgresqlHost: e-shop-postgres
  postgresqlPort: 5432