apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  annotations:
    prometheus.io/path: /actuator/prometheus
    prometheus.io/scrape: "true"
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: "TCP"
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}