apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.deployment.serverPort }}
          env:
            - name: DB_HOST
              valueFrom:
               configMapKeyRef:
                name: {{ .Chart.Name }}-postgres-config
                key: host
            - name: DB_NAME
              valueFrom:
               configMapKeyRef:
                name: {{ .Chart.Name }}-postgres-config
                key: name
            - name: POSTGRES_USER
              valueFrom:
               secretKeyRef:
                name: {{ .Chart.Name }}-postgres-secret
                key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
               secretKeyRef:
                name: {{ .Chart.Name }}-postgres-secret
                key: postgres_password
      imagePullSecrets:
        - name: regcred