apiVersion: v1
kind: Service
metadata:
  name: e-shop
  annotations:
    prometheus.io/path: /actuator/prometheus
    prometheus.io/scrape: "true"
spec:
  selector:
    app: e-shop
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 8000
  type: LoadBalancer