apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-shop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: e-shop
  template:
    metadata:
      labels:
        app: e-shop
    spec:
      containers:
        - name: e-shop
          image: angryjavadeveloper/e-shop:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              valueFrom:
               configMapKeyRef:
                name: postgres-config
                key: host
            - name: DB_NAME
              valueFrom:
               configMapKeyRef:
                name: postgres-config
                key: name
            - name: POSTGRES_USER
              valueFrom:
               secretKeyRef:
                name: postgres-access
                key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
               secretKeyRef:
                name: postgres-access
                key: postgres_password
      imagePullSecrets:
        - name: regcred